version: '3'
services:
  influxdb_test:
    image: influxdb:latest
    container_name: influxdb_test
    environment:
      - INFLUXDB_DB=${INFLUXDB_DATABASE}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
    ports:
      - "8086:8086"
    volumes:
      - database_influx_test:/var/lib/influxdb
    networks:
      - api_test

  postgres_test:
    image: postgres:latest
    container_name: db_postgres_test
    environment:
      - POSTGRES_USER=${TEST_DB_USER}
      - POSTGRES_PASSWORD=${TEST_DB_PASSWORD}
      - POSTGRES_DB=${TEST_DB_NAME}
      - DATABASE_HOST=${TEST_DB_HOST}
    ports:
      - '5555:5432'
    volumes:
      - database_postgres_test:/var/lib/postgresql/data
    networks:
      - api_test

  backend_test:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.test
    env_file:
      - ./.env
    volumes:
      - back_test:/backend
    depends_on:
      - postgres_test
      - influxdb_test
    links:
      - postgres_test
      - influxdb_test
    networks:
      - api_test

volumes:
  back_test:
  database_postgres_test:
  database_influx_test:

networks:
  api_test:
    driver: bridge
