version: "3.3"
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    environment:
      - INFLUXDB_HOST=${INFLUXDB_HOST}
      - INFLUXDB_DB=${INFLUXDB_DATABASE}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
    ports:
      - "8086:8086"
    volumes:
      - database_influx:/var/lib/influxdb
    networks:
      - api

  postgres:
    image: postgres:latest
    container_name: db_postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - '6000:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - api

  openflight_core:
    container_name: openflight_core
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    env_file:
      - ./.env
    command: ["./main"]
    ports:
      - '8000:8000'
    volumes:
      - openflight_core:/core
    depends_on:
      - postgres
      - influxdb
    links:
      - postgres
      - influxdb
    networks:
      - api

volumes:
  openflight_core:
  database_postgres:
  database_influx:

networks:
  api:
    driver: bridge
