version: '3'
services:
  postgres_test:
    image: postgres:latest
    container_name: db_postgres_test
    environment:
      - POSTGRES_USER=${TEST_DB_USER}
      - POSTGRES_PASSWORD=${TEST_DB_PASSWORD}
      - POSTGRES_DB=${TEST_DB_NAME}
      - DATABASE_HOST=${TEST_DB_HOST}
    ports:
      - '5555:5432'
    volumes:
      - database_postgres_test:/var/lib/postgresql/data
    networks:
      - api_test

  backend_test:
    build:
      context: .
      dockerfile: ./Dockerfile.test
    volumes:
      - back_test:/backend
    depends_on:
      - postgres_test
    links:
      - postgres_test
    networks:
      - api_test

volumes:
  back_test:
  database_postgres_test:

networks:
  api_test:
    driver: bridge
