name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get code
      uses: actions/checkout@v2
    - name: Build and publish
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
          name: ${{ secrets.REGISTRY_NAME }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          dockerfile: docker/Dockerfile
    - name: Deploy
      uses: appleboy/ssh-action@master
      env:
        TARGET_PATH: ${{ secrets.SERVER_TARGET_PATH }}
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        envs: TARGET_PATH
        script: |
          cd $TARGET_PATH
          docker-compose pull openflight_core
          docker-compose up --no-deps -d openflight_core
          
